#!/usr/bin/bash

if ! command -v heif-convert &> /dev/null; then
    echo "heif-convert could not be found. Please install it first."
    exit 1
fi


if [ -z "$1" ]; then
    echo "Error: No directory provided."
    echo "Usage: $0 /path/to/directory"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "Error: $1 is not a valid directory."
    exit 1
fi

TARGET_DIR="$1"

echo "Starting conversion in directory: $TARGET_DIR"

#TODO: make convertion parallel
find "$TARGET_DIR" -type f \( -iname "*.heic" -o -iname "*.HEIC" \) | while IFS= read -r file; do
    jpg_file="${file%.heic}.jpg"
    if heif-convert "$file" "$jpg_file"; then
        echo "Conversion successful: $file -> $jpg_file"
        rm "$file"
    else
        echo "Conversion failed for $file. Keeping the original file."
    fi
done
